---
spring:
  application:
    name: product-service
server:
  port: 10001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoint:
    health:
      show-details: always